# Generated by Django 4.2 on 2025-08-07 11:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Absent', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customAuth.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
