# Generated by Django 4.2 on 2025-08-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0002_attendancelog_delete_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(default='Present', max_length=10),
        ),
    ]
